#pragma once
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#undef TAPPING_TERM
#define TAPPING_TERM 175
// #define TAPPING_TERM_PER_KEY
// #define LONG_TAPPING_TERM 300
// #define PERMISSIVE_HOLD
// #define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD_PER_KEY
// #define RETRO_TAPPING_PER_KEY
#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

// #define RGBLIGHT_LAYERS
// #define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
// #define RGBLIGHT_ANIMATIONS

// #define RGBLIGHT_LIMIT_VAL 10
