MOUSEKEY_ENABLE = no # Mouse keys
COMMAND_ENABLE =no
# BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE=no
AUDIO_ENABLE=no
 KEY_OVERRIDE_ENABLE = yes
# RGB_MATRIX_ENABLE = yes
# RGBLIGHT_ENABLE = yes
#  AUTO_SHIFT_ENABLE = yes # Auto Shift

# Saves a bunch of memory
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no
VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
